name: Render Template Files

on:
  create:
    # This will trigger when the main branch is created (typically at repository creation)
    branches:
      - devel
  push:
    # This will also run on the first push
    branches:
      - main
  repository_dispatch:
    # This allows triggering via repo creation webhook if configured
    types: [repository-created]
  workflow_dispatch:  # Allows manual triggering

jobs:
  render-templates:
    runs-on: ubuntu-latest
    permissions:
      workflows: write
      actions: write
      attestations: write
      checks: write
      contents: write
      deployments: write
      discussions: write
      issues: write
      metadata: write
      models: write
      packages: write
      pages: write
      pull-requests: write
      security-events: write
      statuses: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          echo "Python"
      
      - name: Run template rendering script
        run: |
          cd .github/workflows
          python render.py
      
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Render templates and replace placeholders" || echo "No changes to commit"
          git push
      
      - name: Remove workflow file
        run: |
          # Remove the workflow file itself
          rm -f .github/workflows/render-template.yml
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .github/workflows/render-template.yml
          git commit -m "Remove one-time workflow file" || echo "No changes to commit"
          git push
